Additional cta
RedTurtle/volto-blocks pull request #4
Opened 2024-11-18 11:51 UTC by sabrina-bongiovanni

After merging this: https://gitlab.com/redturtle/qubicaamf/qubicaamf-project/-/merge_requests/1

2024-11-18 13:18 UTC, pnicolli requested changes
The import change is to be done everywhere

2024-11-18 13:18 UTC, pnicolli commented on packages/volto-blocks/src/components/blocks/CallToAction/Edit.tsx
> +import CTA from '../commons/CTA';
```suggestion
import CTA from '@redturtle/volto-blocks/components/blocks/commons/CTA';
```

2024-11-18 13:18 UTC, pnicolli commented on packages/volto-blocks/src/components/blocks/commons/CTA.tsx
> +    <div>
I would add at least one generic class to allow styling. Something a little bit specific to avoid conflicts, like `blocks-cta`

2024-11-18 15:09 UTC, sabrina-bongiovanni commented on packages/volto-blocks/src/components/blocks/CallToAction/Edit.tsx
> +import CTA from '../commons/CTA';
changed in all components

2024-11-18 15:09 UTC, sabrina-bongiovanni commented on packages/volto-blocks/src/components/blocks/commons/CTA.tsx
> +    <div>
done!

2024-11-21 08:49 UTC, pnicolli approved these changes

2024-11-21 09:04 UTC, pnicolli approved these changes

2024-11-21 09:08 UTC, merged